# Generated by Django 3.1.4 on 2020-12-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201206_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('child', 'Child'), ('adult', 'Adult')], default='child', max_length=20, null=True),
        ),
    ]
