# Generated by Django 3.1.4 on 2020-12-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='type',
        ),
    ]
