# Generated by Django 3.1.4 on 2020-12-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.CharField(choices=[('1', '1')], default='age not set', max_length=30, null=True),
        ),
    ]
