# Generated by Django 3.1.4 on 2020-12-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201208_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='/static/users.png', null=True, upload_to='users'),
        ),
    ]
