# Generated by Django 3.1.4 on 2020-12-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('pic', 'Drawing'), ('mod', 'Hand-made model')], default=None, max_length=7),
        ),
    ]
